export interface TrendingAd {
  id: string;
  title: string;
  category: string;
  platform: string;
  description: string;
  whyItWorks: string;
  format: string;
  hook: string;
  cta: string;
  icon: string;
  color: string;
  trendScore: number;
  industries: string[];
  tips: string[];
}

export const TRENDING_ADS: TrendingAd[] = [
  {
    id: 'ta1',
    title: 'Before & After Transformation',
    category: 'Social Proof',
    platform: 'Instagram / TikTok',
    format: 'Short Video (15-30s)',
    description: 'Split-screen showing dramatic before and after results. Customer face reveal with emotional reaction builds instant trust and relatability.',
    whyItWorks: 'Visual proof eliminates skepticism. The emotional journey creates connection and FOMO in one hit.',
    hook: '"I can\'t believe this happened in just [X] days..."',
    cta: 'Get the same results →',
    icon: 'compare',
    color: '#00C853',
    trendScore: 98,
    industries: ['Beauty', 'Fitness', 'Health', 'Home Improvement'],
    tips: ['Show real unfiltered results', 'Add customer name + days taken', 'Use emotional music'],
  },
  {
    id: 'ta2',
    title: 'Unboxing Experience Ad',
    category: 'E-Commerce',
    platform: 'TikTok / YouTube',
    format: 'POV Video (30-60s)',
    description: 'First-person POV unboxing of the product — shows packaging quality, reveals contents, and creates desire through tactile visual experience.',
    whyItWorks: 'Triggers ASMR dopamine response. Customers feel like they\'re receiving the package, driving instant purchase urge.',
    hook: '"You won\'t believe what arrived today 🤯"',
    cta: 'Order yours at the link in bio',
    icon: 'inventory',
    color: '#FF6B35',
    trendScore: 96,
    industries: ['E-Commerce', 'Subscription Boxes', 'Electronics', 'Fashion'],
    tips: ['High-quality packaging matters', 'Show close-up textures', 'React genuinely'],
  },
  {
    id: 'ta3',
    title: 'UGC-Style Testimonial',
    category: 'Trust Building',
    platform: 'Facebook / Instagram',
    format: 'Vertical Video (15-30s)',
    description: 'Real customer talking directly to camera sharing their genuine experience. Shot on phone in natural setting — intentionally lo-fi to feel authentic.',
    whyItWorks: 'Peer-to-peer trust is 10× stronger than brand messaging. Authenticity over polish wins every time.',
    hook: '"Okay I have to tell you about this..."',
    cta: 'See why 10,000+ people love it',
    icon: 'record-voice-over',
    color: '#FFD700',
    trendScore: 97,
    industries: ['All Industries', 'SaaS', 'Beauty', 'Health', 'Services'],
    tips: ['Natural lighting only', 'No scripts — let them talk freely', 'Subtitles are essential'],
  },
  {
    id: 'ta4',
    title: 'Problem Agitation Solution (PAS)',
    category: 'Direct Response',
    platform: 'Facebook / Google',
    format: 'Static Image + Copy',
    description: 'Three-panel ad: Panel 1 shows the painful problem, Panel 2 makes the frustration worse, Panel 3 delivers the product as the obvious solution.',
    whyItWorks: 'Mirrors the customer\'s inner dialogue. They feel deeply understood before the solution is even presented.',
    hook: 'Still struggling with [problem]? You\'re not alone.',
    cta: 'Fix it in [timeframe] — Start Free',
    icon: 'psychology',
    color: '#7B2FBE',
    trendScore: 95,
    industries: ['SaaS', 'Services', 'Health', 'Finance', 'Productivity'],
    tips: ['Be brutally specific about the problem', 'Use customer language not marketing speak', 'Proof in the solution panel'],
  },
  {
    id: 'ta5',
    title: 'Countdown Flash Sale',
    category: 'E-Commerce',
    platform: 'All Platforms',
    format: 'Animated Banner + Video',
    description: 'Animated countdown timer overlaid on product with bold discount text. Creates genuine urgency with real deadline. Works for limited stock too.',
    whyItWorks: 'Loss aversion is more powerful than gain. "Ending soon" triggers immediate action vs "buy now" alone.',
    hook: '⚡ [X]% OFF ends in 02:47:33',
    cta: 'Claim Before It\'s Gone',
    icon: 'timer',
    color: '#FF1744',
    trendScore: 94,
    industries: ['E-Commerce', 'Retail', 'Food & Beverage', 'Events'],
    tips: ['Make the timer real — don\'t fake scarcity', 'Show original vs sale price', 'Bold red/orange colors'],
  },
  {
    id: 'ta6',
    title: '"Day In The Life" Brand Story',
    category: 'Brand Awareness',
    platform: 'Instagram / TikTok',
    format: 'Video Series (3-5 clips)',
    description: 'Behind-the-scenes content showing how the product fits into a real aspirational lifestyle. Not selling — storytelling. The product appears naturally.',
    whyItWorks: 'People buy identities, not products. If they see themselves in the story, purchase is the next logical step.',
    hook: '"My morning routine with [Product]"',
    cta: 'Link in bio to get yours',
    icon: 'video-library',
    color: '#00D4FF',
    trendScore: 93,
    industries: ['Fashion', 'Wellness', 'Food', 'Tech Gadgets', 'Fitness'],
    tips: ['Show aspirational but achievable life', 'Product use should feel natural not staged', 'Build a series for repeat exposure'],
  },
  {
    id: 'ta7',
    title: 'Expert / Authority Content Ad',
    category: 'B2B / Trust',
    platform: 'LinkedIn / YouTube',
    format: 'Long Form Video (2-5 min)',
    description: 'Founder or expert shares genuinely valuable industry insight. 80% pure value, 20% soft pitch at the end. Position as the go-to authority.',
    whyItWorks: 'Reciprocity principle — people who receive real value feel compelled to give back through conversion.',
    hook: '"The [industry] mistake costing you $[X] monthly"',
    cta: 'Get our free [resource] to fix this',
    icon: 'school',
    color: '#0A66C2',
    trendScore: 91,
    industries: ['B2B', 'SaaS', 'Consulting', 'Finance', 'Legal', 'Medical'],
    tips: ['Be genuinely helpful — no fake value', 'Specific numbers increase credibility', 'Soft CTA feels more trustworthy'],
  },
  {
    id: 'ta8',
    title: 'Comparison Ad',
    category: 'Competitive',
    platform: 'Google / Facebook',
    format: 'Static Image / Carousel',
    description: 'Side-by-side comparison table showing your product vs competitors or "old way vs new way." Clear winner positioning without naming competitors.',
    whyItWorks: 'Reduces cognitive load — customers don\'t have to research. You present the decision with your product winning.',
    hook: 'Why [X,000] people switched from [old way]',
    cta: 'See the full comparison',
    icon: 'compare-arrows',
    color: '#FF6B35',
    trendScore: 90,
    industries: ['SaaS', 'E-Commerce', 'Tech', 'Financial Products', 'Healthcare'],
    tips: ['Never name competitors directly', 'Keep comparison honest — credibility matters', 'Checkmarks beat text every time'],
  },
  {
    id: 'ta9',
    title: 'Interactive Poll / Question Ad',
    category: 'Engagement',
    platform: 'Instagram Stories / Facebook',
    format: 'Stories Interactive',
    description: 'Stories ad with built-in poll, quiz, or question sticker. Ask something relevant to your audience\'s pain. Low commitment entry point.',
    whyItWorks: 'Participation creates ownership bias. Once someone engages with a poll, they\'re 4× more likely to visit your profile.',
    hook: 'Which one is your biggest challenge? 👇',
    cta: 'We solve [winning answer] — tap to learn how',
    icon: 'poll',
    color: '#E1306C',
    trendScore: 89,
    industries: ['Beauty', 'Health', 'SaaS', 'Education', 'Fitness'],
    tips: ['Make poll choices resonate deeply', 'Follow up with a DM to poll responders', 'Use insights to improve targeting'],
  },
  {
    id: 'ta10',
    title: 'Social Proof Number Ad',
    category: 'Trust / FOMO',
    platform: 'All Platforms',
    format: 'Static Image / Short Video',
    description: 'Lead with a specific impressive number — customers, reviews, results, or sales. The number does the convincing before a word is read.',
    whyItWorks: 'Herd mentality: if thousands choose this, it must be the right choice. Numbers feel more honest than claims.',
    hook: '"47,832 people downloaded this in the last 30 days"',
    cta: 'Join them — it\'s free to start',
    icon: 'leaderboard',
    color: '#00C853',
    trendScore: 92,
    industries: ['SaaS', 'E-Commerce', 'Apps', 'Services', 'Education'],
    tips: ['Real specific numbers (47,832 vs 50,000)', 'Pair with 5-star rating visual', 'Update numbers regularly'],
  },
  {
    id: 'ta11',
    title: 'Founder Story Ad',
    category: 'Brand Story',
    platform: 'Facebook / Instagram',
    format: 'Video (60-90s)',
    description: 'Founder tells the personal origin story — the pain they felt, why they built the product, and who they built it for. Raw and emotional.',
    whyItWorks: 'Humans buy from humans they trust. A vulnerable founder story builds emotional connection no celebrity endorsement can match.',
    hook: '"I was embarrassed to admit I had this problem..."',
    cta: 'Read my full story',
    icon: 'person',
    color: '#FF6B35',
    trendScore: 88,
    industries: ['DTC Brands', 'Health', 'Beauty', 'Apparel', 'Mission-Driven Brands'],
    tips: ['Be vulnerable — perfection repels connection', 'Show the exact moment the idea was born', 'End with who you\'re building it for'],
  },
  {
    id: 'ta12',
    title: 'Trending Sound / Format Duet',
    category: 'Viral Content',
    platform: 'TikTok',
    format: 'TikTok 15-30s',
    description: 'Adapt currently trending TikTok sounds, formats, or challenges and seamlessly integrate your product. Native-feeling content that rides the algorithm.',
    whyItWorks: 'TikTok rewards using trending sounds with 3-10× more reach. The familiar format lowers ad resistance.',
    hook: 'POV: you just discovered [Product] 🤯',
    cta: 'Link in bio before it sells out',
    icon: 'music-video',
    color: '#FF0050',
    trendScore: 96,
    industries: ['Fashion', 'Food', 'Beauty', 'Entertainment', 'Apps'],
    tips: ['Check trending sounds weekly — act fast', 'Keep it native — no obvious brand overlay', 'Use trending hashtags + your niche tags'],
  },
  {
    id: 'ta13',
    title: 'Abandoned Cart Recovery Ad',
    category: 'Retargeting',
    platform: 'Facebook / Google',
    format: 'Dynamic Retargeting',
    description: 'Dynamic ad showing the exact product the user viewed, with a personalized message addressing common objections + a small incentive to return.',
    whyItWorks: 'Abandoned cart visitors are your hottest leads — 80% left due to distraction, not firm decision. One reminder converts 15-20%.',
    hook: '"You left something behind... here\'s 10% off to come back"',
    cta: 'Complete your purchase →',
    icon: 'shopping-cart',
    color: '#FF1744',
    trendScore: 97,
    industries: ['E-Commerce', 'Fashion', 'Electronics', 'Home', 'Beauty'],
    tips: ['Retarget within 1-24 hours', 'Address top 3 objections in copy', 'Small discount (10-15%) is enough trigger'],
  },
  {
    id: 'ta14',
    title: 'Free Value Lead Magnet Ad',
    category: 'Lead Generation',
    platform: 'Facebook / LinkedIn',
    format: 'Lead Generation Form Ad',
    description: 'Promote a free resource (checklist, guide, template, tool) and capture email directly in the ad without leaving the platform.',
    whyItWorks: 'Free removes all friction. Lead gen form ads keep users in-app = 40% higher conversion rate vs landing pages.',
    hook: '"Free [Resource]: The [Topic] Checklist That [Result]"',
    cta: 'Get It Free — No Spam Ever',
    icon: 'download',
    color: '#00D4FF',
    trendScore: 90,
    industries: ['B2B', 'SaaS', 'Consulting', 'Education', 'Real Estate'],
    tips: ['Lead magnet must solve ONE specific problem', 'Deliver instantly via email', 'Warm them up with email sequence after'],
  },
  {
    id: 'ta15',
    title: 'Product Demo / Tutorial Ad',
    category: 'Education',
    platform: 'YouTube / Facebook',
    format: 'Video (60-180s)',
    description: 'Shows the product being used to solve a real problem in real-time. No fluff — just the product doing exactly what it promises.',
    whyItWorks: 'Seeing is believing. Product demos reduce purchase anxiety by answering "will this actually work for me?" before checkout.',
    hook: '"Watch me [achieve result] in under [timeframe]"',
    cta: 'Get the same tool — link below',
    icon: 'play-lesson',
    color: '#FF0000',
    trendScore: 89,
    industries: ['Tech', 'SaaS', 'Home Products', 'Beauty Tools', 'Fitness Equipment'],
    tips: ['Show real messy problem first', 'No cuts — single take feels authentic', 'Address the #1 doubt during demo'],
  },
  {
    id: 'ta16',
    title: 'Limited Edition / Scarcity Drop',
    category: 'Product Launch',
    platform: 'Instagram / Email',
    format: 'Announcement Image + Story',
    description: 'Announce a strictly limited product run — specific number of units, specific window. FOMO at maximum. Community-exclusive launch creates tribe loyalty.',
    whyItWorks: 'Scarcity triggers primal fear of missing out. Limited drops consistently sell out 10× faster than open inventory.',
    hook: '"Only 500 units. Never restocked."',
    cta: 'Drop goes live [Date/Time] — set reminder',
    icon: 'diamond',
    color: '#FFD700',
    trendScore: 91,
    industries: ['Fashion', 'Sneakers', 'Art', 'Food', 'Gaming', 'Beauty'],
    tips: ['Build anticipation 1-2 weeks before', 'Countdown posts create excitement', 'Show behind-the-scenes creation'],
  },
  {
    id: 'ta17',
    title: 'Influencer Reaction / Review',
    category: 'Influencer Marketing',
    platform: 'TikTok / Instagram',
    format: 'Collab Video (30-60s)',
    description: 'Micro-influencer receives and genuinely reacts to the product on camera. Real first impressions, honest reactions, authentic audience connection.',
    whyItWorks: 'Micro-influencers (5k-50k) have 60% higher engagement than mega-influencers. Niche audiences trust their opinion implicitly.',
    hook: '"The brand actually sent me this to try..."',
    cta: 'Tag a friend who needs this 👇',
    icon: 'star',
    color: '#E1306C',
    trendScore: 93,
    industries: ['Beauty', 'Food', 'Tech', 'Fitness', 'Fashion', 'Home'],
    tips: ['Micro > macro for engagement', 'Give creative freedom — don\'t over-brief', 'Repurpose as paid whitelisted ads'],
  },
  {
    id: 'ta18',
    title: 'Google Search Responsive Ad',
    category: 'Search / Intent',
    platform: 'Google Search',
    format: 'Text Ad (RSA)',
    description: 'Multiple headlines and descriptions that Google dynamically combines to match search intent. Covers high-intent buying keywords at the moment of decision.',
    whyItWorks: 'Captures bottom-of-funnel buyers at peak purchase intent. Search ads convert 5-10× better than social for transactional keywords.',
    hook: '[Product] — [Key Benefit] | From $[Price]',
    cta: 'Get Free Quote | Shop Now | Try Free',
    icon: 'search',
    color: '#4285F4',
    trendScore: 95,
    industries: ['All Industries', 'Local Services', 'SaaS', 'E-Commerce', 'B2B'],
    tips: ['15 headlines + 4 descriptions = more data', 'Include price in headline to qualify clicks', 'Match landing page to ad copy exactly'],
  },
  {
    id: 'ta19',
    title: 'Email Subject Line Curiosity Gap',
    category: 'Email Marketing',
    platform: 'Email',
    format: 'Email Campaign',
    description: 'Email with a subject line that creates information gap — leaves out the key detail that the audience desperately wants. Open rate skyrockets.',
    whyItWorks: 'The brain physically needs to close information gaps. Curiosity is involuntary — they HAVE to open it.',
    hook: '"The thing I wish someone had told me about [Topic]..."',
    cta: 'Read the full breakdown →',
    icon: 'email',
    color: '#FF6B35',
    trendScore: 87,
    industries: ['All Industries', 'SaaS', 'E-Commerce', 'Media', 'Finance'],
    tips: ['Never clickbait — deliver on the promise', 'Test 3-5 subject line variants', 'Short subject lines under 50 chars win mobile'],
  },
  {
    id: 'ta20',
    title: 'Story Arc Sequential Ad',
    category: 'Retargeting',
    platform: 'Facebook / YouTube',
    format: 'Ad Sequence (3-part)',
    description: 'Three-part ad story delivered over 7 days: Ad 1 — Problem (cold), Ad 2 — Solution (warm), Ad 3 — Offer (hot). Tells a complete persuasion story.',
    whyItWorks: 'Sequential storytelling mimics human conversation. Each touchpoint builds on the last for exponentially higher conversion.',
    hook: 'Part 1: "Does this sound familiar?"',
    cta: 'Part 3: "Here\'s your exclusive offer — 48 hrs only"',
    icon: 'subscriptions',
    color: '#7B2FBE',
    trendScore: 88,
    industries: ['SaaS', 'E-Commerce', 'Health', 'Education', 'Finance'],
    tips: ['Frequency cap at 3-4 views per ad', 'Exclude converters from subsequent parts', 'Each ad must stand alone too'],
  },
  {
    id: 'ta21',
    title: 'App Install Playable Ad',
    category: 'Mobile Apps',
    platform: 'Meta / Google / TikTok',
    format: 'Playable / Interactive',
    description: 'Let users play a mini version of the game or interact with the app before downloading. Qualified installs only — users who play are 3× more likely to retain.',
    whyItWorks: 'Zero-risk trial eliminates "will I like it?" doubt. Interactivity creates dopamine investment before install.',
    hook: '"Try before you install — 100% free"',
    cta: 'I love it — Download now!',
    icon: 'sports-esports',
    color: '#FF1744',
    trendScore: 94,
    industries: ['Mobile Games', 'Apps', 'Fitness', 'Education', 'Productivity'],
    tips: ['Show your core loop in 30 seconds', 'End with "want more?" moment', 'Reward the player within the trial'],
  },
  {
    id: 'ta22',
    title: 'Local Area Geotargeted Ad',
    category: 'Local Business',
    platform: 'Facebook / Google',
    format: 'Static + Map Extension',
    description: 'Hyper-targeted ad within 1-5km radius of business location. Shows map, distance from user, current hours, and specific local offer.',
    whyItWorks: 'Relevance = conversions. "Near you now" is the most powerful local trigger — combines proximity urgency with local trust.',
    hook: '"[Business] is just [X] minutes from you — open now"',
    cta: 'Get Directions | Call Now | Book Today',
    icon: 'location-on',
    color: '#00C853',
    trendScore: 86,
    industries: ['Restaurants', 'Retail', 'Medical Clinics', 'Salons', 'Gyms', 'Auto'],
    tips: ['Use map extension + call extension', 'Target during business hours only', 'Hyperlocal specific neighborhood names'],
  },
  {
    id: 'ta23',
    title: 'Case Study Result Ad',
    category: 'B2B / Proof',
    platform: 'LinkedIn / Facebook',
    format: 'Carousel or Long-form',
    description: 'Detailed customer success story with specific before/after metrics. Named company, real numbers, direct quote. Every slide = one key result.',
    whyItWorks: 'B2B buyers require proof before committing. Specific metrics (not vague claims) directly answer "will this work for MY company?"',
    hook: 'How [Company] grew revenue [X]% in 90 days using [Product]',
    cta: 'Read the full case study →',
    icon: 'trending-up',
    color: '#0A66C2',
    trendScore: 85,
    industries: ['B2B SaaS', 'Marketing Agencies', 'Consulting', 'Finance', 'HR Tech'],
    tips: ['Get explicit permission to use client name', 'Specific percentages beat vague "significantly"', 'Include direct client quote with photo'],
  },
  {
    id: 'ta24',
    title: 'Meme / Humor Format Ad',
    category: 'Brand Awareness',
    platform: 'TikTok / Twitter / Reddit',
    format: 'Image Meme or Short Video',
    description: 'Brand-relevant meme that makes the audience laugh before they realize it\'s an ad. Shares and saves happen organically. Brand becomes culturally relevant.',
    whyItWorks: 'Humor bypasses ad resistance entirely. A shared meme reaches friends who never knew your brand — free amplification.',
    hook: '"when [relatable pain] hits different 😭"',
    cta: '[Product] — for when this happens IRL (link in bio)',
    icon: 'mood',
    color: '#FFD700',
    trendScore: 87,
    industries: ['Consumer Apps', 'Food', 'Fashion', 'Entertainment', 'DTC Brands'],
    tips: ['Be actually funny — not try-hard', 'Meme must work without the product too', 'React to trending cultural moments fast'],
  },
  {
    id: 'ta25',
    title: 'Medical / Healthcare Trust Ad',
    category: 'Medical',
    platform: 'Google / Facebook',
    format: 'Image + Long Copy',
    description: 'Compliance-friendly healthcare ad featuring doctor endorsement, clinical evidence, patient testimonials, and clear benefit claims with disclaimers.',
    whyItWorks: 'Medical decisions require high trust. Authority signals (doctor, credentials, studies) dramatically reduce purchase hesitation.',
    hook: '"Board-Certified [Specialty] recommends [Product] for [Condition]"',
    cta: 'Book Free Consultation | Learn More',
    icon: 'local-hospital',
    color: '#00C853',
    trendScore: 84,
    industries: ['Clinics', 'Pharmaceutical', 'Wellness', 'Medical Devices', 'Telehealth'],
    tips: ['All claims must be evidence-based', 'Include required medical disclaimers', 'Doctor photo + credentials essential'],
  },
];

export const TRENDING_AD_CATEGORIES = [
  'All', 'Social Proof', 'E-Commerce', 'Direct Response', 'Brand Awareness',
  'B2B / Trust', 'Retargeting', 'Lead Generation', 'Mobile Apps', 'Local Business',
  'Email Marketing', 'Viral Content', 'Medical',
];
